added Github Action for pack and store provider package in ghcr, and …
web-seven/provider-magento pull request #11
Opened 2024-06-11 11:39 UTC by ca7alindev

…generate magento types

2024-06-11 12:14 UTC, evghen1 requested changes

2024-06-11 12:14 UTC, evghen1 commented on .github/workflows/release.yaml
> +            done
@ca7alindev Please move it into normal bash script or into Makefile, i will be required to test it, not sure run it in GHA is best idea for this.

2024-06-11 12:14 UTC, evghen1 commented on scheme.json
@ca7alindev Is done manually or by script downloaded from Magento API?

2024-06-11 13:24 UTC, ca7alindev commented on scheme.json
@evghen1 is downloaded manually

2024-07-01 15:58 UTC, evghen1 approved these changes

2024-07-01 15:58 UTC, merged