generated Magento and Categories apis from crossplane template, added…
web-seven/provider-magento pull request #3
Opened 2024-04-29 12:51 UTC by ca7alindev

Generated Magento and Categories apis from crossplane template, added Magento and Categories api schema to schema builder and configured parameters of Category type.

2024-04-29 14:42 UTC, evghen1 requested changes

2024-04-29 14:42 UTC, evghen1 commented on Makefile
>  PROJECT_REPO := github.com/crossplane/$(PROJECT_NAME)
@ca7alindev replace crossplane with web-seven

2024-04-29 14:42 UTC, evghen1 commented on .github/workflows/ci.yml
> +          make check-diff || true
@ca7alindev Not sure is good idea to simple ignore errors, what that will teach you, just make hack, but not understand how it works.
Please make it works, if it works in other providers based on this template, check there how they made it.

2024-04-29 14:42 UTC, evghen1 commented on .github/workflows/ci.yml
> -          file: _output/tests/linux_amd64/coverage.txt
@ca7alindev Why you remove this step?

2024-04-29 14:42 UTC, evghen1 commented on .github/workflows/ci.yml
> +          make check-diff || true
eg. this: https://github.com/crossplane-contrib/provider-sql

2024-04-29 14:42 UTC, evghen1 commented on apis/categories/categories.go
> +package categories
@ca7alindev package and api shall be named in singular noun.

2024-04-29 14:42 UTC, evghen1 commented on apis/categories/v1alpha1/category_types.go
> +Copyright 2022 The Crossplane Authors.
@ca7alindev Replace copyrights to Web Seven license.

2024-04-29 14:42 UTC, evghen1 commented on apis/categories/v1alpha1/doc.go
> +Copyright 2022 The Crossplane Authors.
@ca7alindev 2022? not 2024?

2024-04-29 14:42 UTC, evghen1 commented on apis/categories/v1alpha1/groupversion_info.go
> +	Group   = "categories.magento.crossplane.io"
@ca7alindev i think group is no crossplane.io, but web7.md not?

2024-04-29 14:42 UTC, evghen1 commented on package/crds/categories.magento.crossplane.io_categories.yaml
> +  name: categories.categories.magento.crossplane.io
@ca7alindev Do not give me auto replaced version, check what you doing. categories, categories, categories, how much categories shall be in name. Please keep developer mind.

2024-04-30 09:56 UTC, ca7alindev commented
@evghen1 the reason that unit-tests is in a runing state so long is because of step "Publish Unit Test Coverage" that requires a token from codecov in order to upload to it:
"This Action also requires you to [provide an upload token](https://docs.codecov.io/docs/frequently-asked-questions#section-where-is-the-repository-upload-token-found-) from [codecov.io](https://www.codecov.io/) (tip: in order to avoid exposing your token, [store it](https://docs.codecov.com/docs/adding-the-codecov-token#github-actions) as a secret)."
https://github.com/codecov/codecov-action

2024-05-01 08:22 UTC, evghen1 approved these changes

2024-05-01 08:23 UTC, merged