Implement reconciliation of category for create/update/delete categor…
web-seven/provider-magento pull request #5
Opened 2024-05-08 15:32 UTC by ca7alindev

2024-05-08 16:02 UTC, evghen1 requested changes
@ca7alindev Rework it using pure REST client.

2024-05-08 16:02 UTC, evghen1 commented on internal/controller/category/category.go
> +	"github.com/hermsi1337/go-magento2/pkg/magento2/categories"
@ca7alindev No,no. This not good, don't use not verified packages. This is no pet project just for fun. Please use pure API calls.

2024-05-08 16:02 UTC, evghen1 commented on apis/category/v1alpha1/category_types.go
> -	ProductCount int    `json:"product_count,omitempty"`
@ca7alindev Why you removed this properties.

2024-05-14 11:09 UTC, evghen1 commented
@ca7alindev any news?

2024-05-14 15:04 UTC, evghen1 requested changes

2024-05-14 15:04 UTC, evgheni7 commented on internal/client/categories/categories.go
@ca7alindev Please add functions descriptions

2024-05-14 15:04 UTC, evgheni7 commented on internal/client/categories/categories.go
> +		Put(path)
@ca7alindev Make function for rest client, do not duplicate code.

2024-05-14 15:04 UTC, evgheni7 commented on internal/controller/category/category.go
>  	fmt.Printf("Observing: %+v", cr)
@ca7alindev Remove prints like this, or add debug flag.

2024-05-14 15:04 UTC, evgheni7 commented on package/crds/category.magento.web7.md_categories.yaml
@ca7alindev Please unify name of CRD files, you mentioned "category" twice.
Shall be magento.web7.md_categories.yaml

2024-05-14 15:04 UTC, evgheni7 commented on internal/controller/category/category.go
> +	isUpToDate, _ := categories.IsCategoryUpToDate(cr.Spec.ForProvider.Name, cr, desired)
@ca7alindev Bad idea to use name for connect resources, in crossplane "external-name" annotation used, check it please how is done in other providers.

2024-05-14 15:04 UTC, evgheni7 commented on internal/client/categories/categories.go
> +func UpdateCategoryByName(c *magento.Client, categoryName string, observed *v1alpha1.Category) error {
@ca7alindev Not sure about name, shall be used original identification, what is ID for RESTful API

2024-05-14 15:04 UTC, evgheni7 commented on examples/sample/category.yaml
> +apiVersion: category.magento.web7.md/v1alpha1
@ca7alindev 
```
apiVersion:  magento.web7.md/v1alpha1
kind: Category

2024-05-14 15:04 UTC, evgheni7 commented on examples/sample/category.yaml
> +    include_in_menu: true
@ca7alindev No underscores

2024-05-14 15:04 UTC, evgheni7 commented on apis/category/v1alpha1/category_types.go
@ca7alindev Rename file to simple apis/v1alpha1/category_types.go
Why we need category word twice here?

2024-05-14 15:04 UTC, evghen1 commented on internal/client/client.go
> +func (c *Client) CreateRestyClient() (*resty.Client, error) {
@ca7alindev Simple Create() don't use customization of methods. This method simple create client.

2024-05-14 15:04 UTC, evghen1 commented on internal/client/categories/categories.go
> +	path := fmt.Sprintf("%s/rest/all/V1/categories/%d", c.BaseURL, category.Spec.ForProvider.ID)
@ca7alindev Use constant for URLs, you duplicate it many times.

2024-05-14 15:04 UTC, evghen1 commented on internal/client/categories/categories.go
> +		"searchCriteria[filterGroups][0][filters][0][value]": categoryName,
@ca7alindev Bad idea, category identifier is ID. Clear is looks like not usable, but you have to keep logic of API, not think like abstract user of your API. Keep standards, that's what is waiting from you by user.

2024-05-16 15:06 UTC, ca7alindev commented on apis/category/v1alpha1/category_types.go
@evghen1 in apis directory already exists v1alpha1 where are all magento provider level apis

2024-05-17 07:27 UTC, evghen1 approved these changes

2024-05-17 07:27 UTC, merged