created universal controller that reconciles all resources related to…
web-seven/provider-magento pull request #7
Opened 2024-05-23 13:35 UTC by ca7alindev

…ed on standard RESTful API definitions

2024-05-23 14:44 UTC, evghen1 requested changes

2024-05-23 14:44 UTC, evghen1 commented on internal/controller/magento.go
> +type connector struct {
@ca7alindev move all types to beginning of file

2024-05-23 14:44 UTC, evghen1 commented on internal/controller/magento.go
> +	newServiceFn func(creds []byte, baseURL string) (*MagentoService, error)
@ca7alindev please rename newServiceFn to something like createMagentoServiceFn

2024-05-23 14:44 UTC, evghen1 commented on internal/controller/magento.go
> +	c.service.client.Path = "/rest/" + strings.ToUpper(mg.GetObjectKind().GroupVersionKind().Version) + "/" + crd.Spec.Names.Plural
@ca7alindev use package constants for this kind of strings like "/rest/"

2024-05-23 14:44 UTC, evghen1 commented on internal/controller/magento.go
> +	externalID := mg.GetAnnotations()["external-id"]
@ca7alindev package use constant for external-id string, because it used many times.

2024-05-24 09:01 UTC, evghen1 requested changes

2024-05-24 09:01 UTC, evgheni7 commented on internal/controller/magento.go
> +	api          = "/rest/"
@ca7alindev Please do not use separators in constants like this. Is not good practice.

2024-05-24 09:01 UTC, evgheni7 commented on internal/controller/magento.go
> +	c.service.client.Path = api + strings.ToUpper(mg.GetObjectKind().GroupVersionKind().Version) + "/" + crd.Spec.Names.Plural
@ca7alindev Best to be used strings.join(paths, separator), where separator is constant.

2024-05-24 09:01 UTC, evgheni7 commented on internal/controller/magento.go
> +	}
@ca7alindev Please make desired structure and simple use it. That's better. 
Keep in mind you doing one of the main thing in this project, take your time and make everything perfect as possible. I don't need non qualitative results, because they will costs a lot to change in the future.

2024-05-24 09:01 UTC, evgheni7 commented on internal/controller/magento.go
> +
@ca7alindev Remove empty line.

2024-05-30 12:04 UTC, evghen1 requested changes

2024-05-30 12:04 UTC, evghen1 commented on internal/controller/magento.go
> +	return gvk.Group == "magento.web7.md" && gvk.Version == "v1alpha1" &&
@ca7alindev Please move Group and Version to constants.

2024-05-30 12:04 UTC, evghen1 commented on internal/client/magento.go
> +	resp, _ := c.Create().R().Get(c.Path + "/" + id)
@ca7alindev Separators to constants please.

2024-05-30 12:54 UTC, evghen1 commented
@ca7alindev Ready for review?

2024-05-30 13:02 UTC, ca7alindev commented
> @ca7alindev Ready for review?

ready

2024-05-30 13:07 UTC, evghen1 approved these changes

2024-05-30 13:07 UTC, merged